/* AUTH NAMES */
export const LOGIN_LOAD = "LOGIN_LOAD";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_CLEAR_ERROR = "LOGIN_CLEAR_ERROR";
export const LOGOUT = "LOGOUT";
/*TABLES NAMES*/
export const SET_TABLES = "SET_TABLES";
export const ADD_TABLE = "ADD_TABLE";
export const DELETE_TABLE = "DELETE_TABLE";
export const CHANGE_TABLE = "CHANGE_TABLE";
export const LOAD_TABLE = "LOAD_TABLE";
export const ERROR_TABLE = "ERROR_TABLE";
export const CLEAR_ERROR_TABLE = "CLEAR_ERROR_TABLE";
/*PRESENTORS NAMES*/
export const SET_PRESENTORS = "SET_PRESENTORS";
export const ADD_PRESENTOR = "ADD_PRESENTOR";
export const DELETE_PRESENTOR = "DELETE_TABLES";
export const CHANGE_PRESENTOR = "CHANGE_PRESENTOR";
export const SET_PRESENTOR_SCHEDULE = "SET_PRESENTOR_SCHEDULE";
export const LOAD_PRESENTOR = "LOAD_PRESENTOR";
export const ERROR_PRESENTOR = "ERROR_PRESENTOR";
export const CLEAR_ERROR_PRESENTOR = "CLEAR_ERROR_PRESENTOR";
/*SCHEDULE NAMES*/
export const SET_SCHEDULE = "SET_SCHEDULE";
export const LOAD_SCHEDULE = "LOAD_SCHEDULE";
export const ERROR_SCHEDULE = "ERROR_SCHEDULE";
export const CLEAR_ERROR_SCHEDULE = "CLEAR_ERROR_SCHEDULE";
export const SET_SCHEDULE_TABLE = "SET_SCHEDULE_TABLE";
export const ADD_SCHEDULE = "ADD_SCHEDULE";
export const GET_CURRENT_SCHEDULE = "GET_CURRENT_SCHEDULE";